version: '3'

services:

  validation-status:
    #build: .
    container_name: validation-status
    image: croweman/openapi-json-response-validator:0.0.4
    command: sh -c "sh wait-for-it.sh http://app:3010/readiness && echo 'We can now validate!'"
    volumes:
      - ./wait-for-it.sh:/app/wait-for-it.sh
  
  app:
    #build: .
    container_name: openapi-json-response-validator
    image: croweman/openapi-json-response-validator:0.0.4
    restart: "on-failure:10"
    volumes:
      - ./invalid-api.yaml:/app/api.yaml
    ports:
      - "3010:3010"
    environment:
      OPENAPI_JSON_RESPONSE_VALIDATOR_PORT: 3010
